extends: google
parserOptions:
    ecmaVersion: 7
rules:
    camelcase: off
    indent:
        - error
        - 4
    new-cap: off
    no-invalid-this: off
    no-throw-literal: off
    no-unused-vars: off
    quotes: off
    require-jsdoc: off
