#!/usr/bin/env perl

use strict;
use warnings;

sub _exec
{
    my ( $cmd, $err ) = @_;

    if ( system(@$cmd) )
    {
        print "@$cmd\n";
        die $err;
    }
    return;
}

_exec( [ $^X, 'bin/my-cookiecutter.pl' ], 'cookiecutter failed.' );

_exec( [ "gmake", "--silent", "-f", "lib/make/build-deps/build-deps.mak" ],
    "build-deps failed!" );
_exec( [ $^X, './bin/gen-helpers-main.pl' ], "gen-helpers-main.pl failed." );

__END__

=head1 COPYRIGHT & LICENSE

Copyright 2018 by Shlomi Fish

This program is distributed under the MIT / Expat License:
L<http://www.opensource.org/licenses/mit-license.php>

=cut
