#!/usr/bin/env perl

use strict;
use warnings;
use autodie;
use lib './lib';
use Shlomif::MySystem qw/ my_exec_perl my_system /;

my_exec_perl( ['bin/my-cookiecutter.pl'], 'cookiecutter failed.' );

my_system( [ "gmake", "--silent", "-f", "lib/make/build-deps/build-deps.mak" ],
    "build-deps failed!" );
my_exec_perl( ['bin/gen-helpers-main.pl'], "gen-helpers-main.pl failed." );

__END__

=head1 COPYRIGHT & LICENSE

Copyright 2018 by Shlomi Fish

This program is distributed under the MIT / Expat License:
L<http://www.opensource.org/licenses/mit-license.php>

=cut
