"Consciousness and craziness and a hypothesis about its origins"
================================================================
Shlomi Fish <shlomif@cpan.org>
Date: 2020-12-14
:Revision: $Id$

[id="consciusness"]
The origins of consciousness and madness
----------------------------------------

It is well known that when individuals of most primate species (including
monkeys!) are separated from their group/tribe, they stop eating and drinking
and become unenergetic and can even die out of thirst or hunger. This
is a very similar phenomenon to https://en.wikipedia.org/wiki/Major_depressive_disorder in
humans.

In order to avoid it humans, who needed to often travel long
distances alone to find mates, food, water, elementary materials,
during their evolution developed a thought
process, where they hallucinated guiding thoughts or even voices of
"gods", "leaders" ("guideline-generators" or "guideline-factories")
which emitted "rules", or even just "guidelines" to entertain them,
guide them, encourage them, amuse them etc. But these were nevertheless nonsentient.

These leaders could be all kind of entities: friends, relatives, pets,
inanimate objects, dead people, abstract concepts (e.g: "love", "clumsiness"),
mythological figures (including polytheistic gods such as
https://en.wikipedia.org/wiki/Zeus or https://en.wikipedia.org/wiki/Asherah ,
but
also non-divine mortals such as https://en.wikipedia.org/wiki/Gilgamesh or
https://en.wikipedia.org/wiki/Solomon or https://en.wikipedia.org/wiki/Aesop )
, as well as https://en.wikipedia.org/wiki/Platonic_idealism[platonic ideals]
and subideals such as "the human", "the child", "the tree", "the oak", "the bird",
"the swallow", etc.

Note that these language-speaking humans, didn't immediately obey these leaders
and guidelines as people who have read about https://en.wikipedia.org/wiki/Sumer[Sumerian history] can tell, but
they used it for reasoning.

From 2000 BC to 1000 BC the https://en.wikipedia.org/wiki/Akkadian_language[Akkadians]
and their extant colonies of https://en.wikipedia.org/wiki/Babylon[Babylon]
and https://en.wikipedia.org/wiki/Assyria[Assyria] developed increasingly
simplified methods of writing, culminating in the https://en.wikipedia.org/wiki/Abjad[Abjad]
(or "Alphabet"),
which was particularly suitable for writing Phoenician,
https://en.wikipedia.org/wiki/Aramaic and other languages which
we now call https://en.wikipedia.org/wiki/Semitic_languages (albeit
the use of "Shem" to describe peoples in the Tanakh and
elsewhere was https://www.shlomifish.org/humour/humanity/ongoing-text.html#the-gate[more political]
)
. As the Alphabet was easy enough to be learnt even by children (and often
was) and there were plenty of clay tablets or stone walls to write using
chalk or other stones (as I can attest from my experiences in
hiking .il and .pa ) many guidelines ("gods") were exchanged there
in the form of messages (or "memes") not unlike
https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/DocBook5/putting-all-cards-on-the-table-2013/departing_pope_about_twitter.xhtml[social media]
in today's world.

One of these "memes" was "אנוכי יהוה אלהיך" (= "anochi yehovah eloheichah" in modern
Hebrew) which
meant "what is and what will be shall be your guideline" (which likely
meant something close to "live in the present and for the future" or "let bygones
be bygones" or even "forget it", "I forgive you", https://www.youtube.com/watch?v=nbY_aP-alkw["no worries"]).
This is now known as the https://en.wikipedia.org/wiki/I_am_the_Lord_thy_God[First commandment].

While being useful (see http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin]
for instance), it was often overrided by other leaders or their guidelines.
Eventually, the people who spoke the Levantine (Aramaic and Phoenician) Semitic dialects
accumulated so many guidelines that they become confused and annoyed. As a result,
the following meta-guideline was added:
https://en.wikipedia.org/wiki/Ten_Commandments[The second commandment]:
"No other leader [or guideline] shall take precedence over me [= The Jehovah Guideline]".
("לא יהיה לך אלהים אחרים על פניי")

This was nice and well, until one day one boy, girl, man or woman, who likely
was taught to read (possibly by himself) I'll call him https://en.wikipedia.org/wiki/Moses[Mosheh]
accidentally read the 2nd commandment **before** he was familiar with the 1st and
interpreted it as:
"The ‘Soul’ Leader said: no other leader or its guideline shall take precedence
over me [= the ‘Soul' Leader! not jehovah, or any other guideline or leader]"
("לא יהיה לך אלהים אחרים על פניי")

So it was self-referential as suspected in
https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach[GEB] and threw
Moses's brain into a short confusion and demoting of the gods and their
guidelines from which there was only one escape: the birth of a human soul or
"ego" or "I-ness" or "center of sentience/consciousness". A personal super-leader.

Moses started hearing mere thoughts instead of voices that sounded real. He
became a https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/ongoing-text.html#terran-vampires--meet--moses-tells-his-story["self-leader"]
or "Ben-elohim". He could better lead his life but on the downside had
to https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/#dont_just_go_with_the_flow[decide to think]
and he could be happy, "down", clinically depressed, hypomanic, manic
or even Schizophrenic.

