[id="main_doc"]
"Consciousness and craziness and a hypothesis about their origins"
==================================================================
Shlomi Fish <shlomif@cpan.org>
:Date: 2020-12-14
:Revision: $Id$

[id="about_this_doc"]
About this document
-------------------

**Note**: This is just a https://en.wikipedia.org/wiki/Hypothesis[hypothesis]
that mashes up several other sources. Even I find it farfetched.

The sources are:

1. https://en.wikipedia.org/wiki/Bicameralism_(psychology)[Julian Jaynes’ Bicameralism]

2. How I perceived https://en.wikipedia.org/wiki/The_Selfish_Gene[The Selfish Gene] and https://en.wikipedia.org/wiki/Memetics[Memetics] based on online conversations and resources.

3. My study of the https://en.wikipedia.org/wiki/Hebrew_Bible[Hebrew Bible] and ancient history.

4. Linguistic insights from learning Hebrew and https://en.wikipedia.org/wiki/Modern_Standard_Arabic[Arabic]

5. Insights from my experience with https://en.wikipedia.org/wiki/Major_depressive_disorder[Major depressive disorder (“MDD”)] and Hypomanias.

6. https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach["Gödel, Escher, Bach"]

[id="consciousness"]
The origins of consciousness and madness
----------------------------------------

It is well known that when individuals of most https://en.wikipedia.org/wiki/Primate[primate] species (including
monkeys!) are separated from their group/tribe, they stop eating and drinking
and become unenergetic and can even die out of thirst or hunger. This
is a very similar phenomenon to
https://en.wikipedia.org/wiki/Major_depressive_disorder[Major depressive disorder (“MDD”)]
in humans.

In order to avoid it, humans, who often needed to travel long distances alone to
find mates, food, water, elementary materials, etc. developed during their
evolution a thought process, where they hallucinated guiding thoughts (or even
voices) of "leaders" (= "guideline-generators") which
emitted "rules", or even just "guidelines" to entertain them, guide them,
encourage them, amuse them, etc. But these humans were nevertheless nonsentient.

These leaders could be all kind of entities: friends, relatives, pets,
inanimate objects, dead people, abstract concepts (e.g: "love", "clumsiness"),
mythological figures (including polytheistic gods such as
https://en.wikipedia.org/wiki/Zeus[Zeus] or https://en.wikipedia.org/wiki/Asherah[Asherah] ,
but
also non-divine mortals such as https://en.wikipedia.org/wiki/Gilgamesh[Gilgamesh] or
https://en.wikipedia.org/wiki/Solomon[Solomon] or https://en.wikipedia.org/wiki/Aesop[Aesop] )
, as well as https://en.wikipedia.org/wiki/Platonic_idealism[platonic ideals]
and subideals such as "the human", "the child", "the tree", "the oak", "the
animal", "the bird", "the swallow", etc.

Note that these language-speaking humans, didn't immediately obey these leaders
and guidelines, as people who have read about https://en.wikipedia.org/wiki/Sumer[Sumerian history] can attest to, but
they still used it for reasoning.

From 2000 BC to 1000 BC the https://en.wikipedia.org/wiki/Akkadian_language[Akkadians]
and their extant colonies of https://en.wikipedia.org/wiki/Babylon[Babylon]
and https://en.wikipedia.org/wiki/Assyria[Assyria] developed increasingly
simplified methods of writing, culminating in the Phoenician
https://en.wikipedia.org/wiki/Abjad[Abjad]
(or vowel-less "Alphabet"),
which was particularly suitable for writing https://en.wikipedia.org/wiki/Canaanite_languages[Canaanite]
https://en.wikipedia.org/wiki/Aramaic[Aramaic] and other languages which
we now call https://en.wikipedia.org/wiki/Semitic_languages[Semitic languages] (albeit
the use of "Shem" to describe peoples in the Tanakh and
elsewhere was https://www.shlomifish.org/humour/humanity/ongoing-text.html#the-gate[more political]
)

As the Alphabet was easy enough to be learnt even by children (and often was)
and there were plenty of clay tablets or stone walls to write using chalk or
other stones (as I can attest from my experiences in hiking .il and .pa ), many
guidelines were exchanged there in the form of messages (or "memes") not unlike
the Internet
https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/#departing_pope_about_twitter[social media]
in today's world.

These guidelines were referred to as https://en.wiktionary.org/wiki/%D7%90%D7%9C#Hebrew[“el”s (אל) in Hebrew] which stems from the
"towards" preposition,
so it meant "direction", "target", "destination" and only meant "a god" later.

A "guideline-generator" was called "eloha" (אלוה) which meant a collection of "el"s,
and whose plural, "elohim" ("אלוהים") now means https://en.wikipedia.org/wiki/God[the monotheisic "God"]
in modern Hebrew. (This is similar to how the modern English word "corporation"
stems from "corpora" which is a Latin plural of "corpus": "body", "person".)

Jaynes notes that the modern Hebrew word for "a king" - https://en.wiktionary.org/wiki/%D7%9E%D7%9C%D7%9A#Hebrew[“melekh” (מלך)] - meant a lesser leader than an "El", and in butchered ancient Hebrew could have meant "go from where!" ("me'ayin lekh") or "reason" or "cause" or "incentive".

One of these guideline generators was "אנוכי יהוה אלהיך" (= "anochi yehovah eloheichah" in modern
Hebrew) which
meant "'he/she/what is and will be' shall be your guideline-generator" (which likely
emitted guidelines close to "live in the present and for the future" or "let bygones
be bygones" or even "forget it", "I forgive you",
https://www.youtube.com/watch?v=fHbRYNriVAA["Let it be"],
https://www.youtube.com/watch?v=CXqWVWHW8dA["Let it go"],
https://www.youtube.com/watch?v=nbY_aP-alkw["no worries"/"hakuna matata"]).
This is now known as the
https://en.wikipedia.org/wiki/I_am_the_Lord_thy_God[First commandment] although
"Dibber" in Hebrew simply means "he/she/what/it spoke".

We can imagine a conversation then to go similar to this:

* Adam: https://en.wikipedia.org/wiki/Ares[Ares] told me to kill you
* Bob: but https://en.wikipedia.org/wiki/Athena[Athena] forbade killing innocent people
* Adam: The god of Justice tells me you are right, I hope you can forgive me
* Bob: "Jehovah" tells me to forgive you.

While being useful (see http://shlomifishswiki.branchable.com/Saladin_Style/[Saladin]
for instance), it was often overridden by other leaders or their guidelines.
As a result, the following meta-guideline or followup for the 1st commandment was
appended to it:
https://en.wikipedia.org/wiki/Ten_Commandments[The second commandment]:
“No other leaders [or guidelines] shall take precedence over me [= The Jehovah Guideline]”.
("לא יהיה לך אלהים אחרים על פניי")

This was nice and well, until one day one boy, girl, man, or woman, who likely
was taught to read (possibly by himself) - I'll call him SoulZero -
accidentally read the Second Commandment **before** he was familiar with the
first. Then he interpreted it as: "The ‘Soul’ Leader said: no other leader or
its guideline shall take precedence over me [= the ‘Soul' Leader!]"

So it was self-referential as suspected in
https://en.wikipedia.org/wiki/G%C3%B6del,_Escher,_Bach["Gödel, Escher, Bach"] and threw
SoulZero's brain into a short confusion and demoting of the leaders and their
guidelines from which there was only one escape: the birth of a human soul aka
"ego" or "I-ness" or "center of sentience/consciousness". A personal meta-leader.

See:

* https://en.wikipedia.org/wiki/The_Origin_of_Consciousness_in_the_Breakdown_of_the_Bicameral_Mind[The Origin of Consciousness in the Breakdown of the Bicameral Mind]
* https://en.wikipedia.org/wiki/Cogito,_ergo_sum[“I think, therefore I am”]

SoulZero started hearing mere thoughts instead of voices that sounded real. He
became a https://www.shlomifish.org/humour/Star-Trek/We-the-Living-Dead/ongoing-text.html#terran-vampires--meet--moses-tells-his-story["self-leader"]
or "Ben-elohim" or https://en.wikipedia.org/wiki/Tukulti-Ninurta_I["king-of-kings"].

The "worst" thing was that it was contagious and soon many people became
sentient. SoulZero and the other self-leaders told their gospel in the form of
"There are no gods? What are you talking about? Hear this: No other leader
shall take precedence over me".

The self-leaders could better lead their life but on the downside had
to https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/#dont_just_go_with_the_flow[decide to think]
and they could be happy, "down", clinically depressed, mildly
depressed, hypomanic, manic or even Schizophrenic.

[id="MDD"]
Clinical depression ( MDD ) and Murder
--------------------------------------

From experience, while I was in
https://en.wikipedia.org/wiki/Major_depressive_disorder[Major depressive disorder ( MDD )],
my mind was void of thoughts and I was constantly seeking
guidance. Moreover, I believed that the advice and the guidance were
absolute "rules" or even dogma, and that I must obey it.

In https://www.shlomifish.org/meta/FAQ/crime_and_punishment.xhtml[Crime and Punishment],
Raskolnikov is described as MDDed and as murdering innocent people.

[id="neviim"]
The nevi'im and amateur philosophers:
-------------------------------------

I believe that "niba" / "hitnabé" ( https://en.wikipedia.org/wiki/Nevi%27im[“Nevi’im”] )
had several different meanings at different stages in ancient Hebrew.

At one point it meant "to be crazy"/"to emit crazy things"
including in today's casual sense or "to seek divine guidance". Initially,
most of them were out-of-control https://en.wikipedia.org/wiki/Schizophrenia[Schizophrenics]
and https://en.wikipedia.org/wiki/Mania[maniacs] but eventually many
of the best Nevi'im were https://en.wikipedia.org/wiki/Hypomania[hypomanic]
at worst, and not only emulated their predecessors or contemporaries
but topped them.

They could have been funny, or exalting, or sexy, or blasphemous.
They often spoke in normal prose or free-form verse.

https://www.chabad.org/library/bible_cdo/aid/16099[Ezekiel chapter no. I] -  -
can be seen as mocking the various previous visions-of-revelations and
doing it so well that people found it incredibly funny. It is also pointless
to derive meaning from it - Ezekiel was just "making shit up".
