"Consciousness and craziness and a hypothesis about its origins"
================================================================
Shlomi Fish <shlomif@cpan.org>
Date: 2020-12-14
:Revision: $Id$

[id="consciusness"]
The origins of consciousness and madness
----------------------------------------

It is well known that when individuals of most primate species (including
monkeys!) are separated from their group/tribe, they stop eating and drinking
and become unenergetic and can even die out of thirst or hunger. This
is a very similar phenomenon to https://en.wikipedia.org/wiki/Major_depressive_disorder in
humans.

In order to avoid it humans during their evolution developed a thought
process, where they hallucinated guiding thoughts or even voices of
"gods", "leaders" ("guideline-generators" or "guideline-factories")
which emitted "rules", or even just "guidelines" to entertain them,
guide them, encourage them, amuse them etc. But they were nevertheless nonsentient.

These leaders could be all kind of entities: friends, relatives, pets,
inanimate objects, dead people, abstract concepts (e.g: "love", "clumsiness"),
mythological figures (including polytheistic gods such as
https://en.wikipedia.org/wiki/Zeus or https://en.wikipedia.org/wiki/Asherah ,
but
also non-divine mortals such as https://en.wikipedia.org/wiki/Gilgamesh or
https://en.wikipedia.org/wiki/Solomon or https://en.wikipedia.org/wiki/Aesop )
, as well as https://en.wikipedia.org/wiki/Platonic_idealism[platonic ideals]
and subideals such as "the human", "the child", "the tree", "the oak", "the bird",
"the swallow", etc.

From 2000 BC to 1000 BC the https://en.wikipedia.org/wiki/Akkadian_language[Akkadians]
and their extant colonies of https://en.wikipedia.org/wiki/Babylon[Babylon]
and https://en.wikipedia.org/wiki/Assyria[Assyria] developed increasingly
simplified methods of writing, culminating in the https://en.wikipedia.org/wiki/Abjad[Abjad]
(or "Alphabet"),
which was particularly suitable for writing Phoenician,
https://en.wikipedia.org/wiki/Aramaic and other languages which
we now call https://en.wikipedia.org/wiki/Semitic_languages (albeit
the use of "Shem" to describe peoples in the Tanakh and
elsewhere was https://www.shlomifish.org/humour/humanity/ongoing-text.html#the-gate[more political]
)
. As the Alphabet was easy enough to be learnt even by children (and often
was) and there were plenty of clay tablets or stone walls to write using
chalk or other stones (as I can attest from my experiences in
hiking .il and .pa ) many guidelines ("gods") were exchanged there
in the form of messages (or "memes") not unlike
https://www.shlomifish.org/philosophy/philosophy/putting-all-cards-on-the-table-2013/DocBook5/putting-all-cards-on-the-table-2013/departing_pope_about_twitter.xhtml[social media]
in today's world.

One of these "memes" was "אנוכי יהוה אלהיך" (= "anochi yehovah eloheichah" in modern
Hebrew) which
meant "what is and what will be shall be your guideline" (which likely
meant something close to "live in the present and for the future" or "let bygones
be bygones" or even "forget it", "I forgive you", "no worries").

Eventually, the people who spoke the Levantine (Aramaic and Phoenician) Semitic dialects
accumulated so many guidelines that they become confused and annoyed. As a result,
the following meta-guideline was developed:
https://en.wikipedia.org/wiki/Ten_Commandments[The second commandment]
"The ‘Soul’ Leader said: no other leader or its guideline shall take precedence
over me [= the ‘Soul' Leader! not jehovah, or any other guideline or leader]"
("לא יהיה לך אלהים אחרים על פניי"

So the 2nd commandment was self-referential
