"Consciousness and craziness and a hypothesis about its origins"
================================================================
Shlomi Fish <shlomif@cpan.org>
Date: 2020-12-14
:Revision: $Id$

[id="consciusness"]
The origins of consciousness and madness
----------------------------------------

It is well known that when individuals of most primate species (including
monkeys!) are separated from their group/tribe, they stop eating and drinking
and become unenergetic and can even die out of thirst or hunger. This
is a very similar phenomenon to https://en.wikipedia.org/wiki/Major_depressive_disorder in
humans.

In order to avoid it humans during their evolution developed a thought
process, where they hallucinated guiding thoughts or even voices of
"gods", "leaders", "rules", or even just "guidelines" to entertain them,
guide them, encourage them, amuse them etc. But they were nevertheless nonsentient.

From 2000 BC to 1000 BC the https://en.wikipedia.org/wiki/Akkadian_language[Akkadians]
and their extant colonies of https://en.wikipedia.org/wiki/Babylon[Babylon]
and https://en.wikipedia.org/wiki/Assyria[Assyria] developed increasingly
simplified methods of writing, culminating in the https://en.wikipedia.org/wiki/Abjad[Abjad]
(or "Alphabet"),
which was particularly suitable for writing Phoenician,
https://en.wikipedia.org/wiki/Aramaic and other languages which
we now call https://en.wikipedia.org/wiki/Semitic_languages (albeit
the use of "Shem" to describe peoples in the Tanakh and
elsewhere was https://www.shlomifish.org/humour/humanity/ongoing-text.html#the-gate[more political]
)
. As the Alphabet was easy enough to be learnt even by children (and often
was) and there were plenty of clay tablets or stone walls to write using
chalk or other stones (as I can attest from my experiences in
hiking .il and .pa )

