#!/bin/sh

xmlformat()
{
	while test -n "$1"; do
	echo xmlformat $1
	xmllint --format  $1  --output $1
	shift
	done
}

odp2xml() # odp -> xml
{
	mkdir introduction_to_cmake-2.odp.d
	unzip -o introduction_to_cmake-2.odp -d introduction_to_cmake-2.odp.d
	xmlformat introduction_to_cmake-2.odp.d/content.xml  introduction_to_cmake-2.odp.d/meta.xml  introduction_to_cmake-2.odp.d/settings.xml  introduction_to_cmake-2.odp.d/styles.xml
}

xml2odp() # xml -> odp
{
	mv introduction_to_cmake-2.odp introduction_to_cmake-2.odp.save
	( cd introduction_to_cmake-2.odp.d; zip -r ../introduction_to_cmake-2.odp . -x *.svn-base)
  	unzip -t introduction_to_cmake-2.odp
}
