odp2xml() # odp -> xml
{
	mkdir cmake-tutorial.odp.d
	unzip -o cmake-tutorial.odp -d cmake-tutorial.odp.d
}

xml2odp() # xml -> odp
{
	( cd cmake-tutorial.odp.d; zip -r ../cmake-tutorial.odp  .)
  	unzip -t cmake-tutorial.odp
}
