$myvar = 17;
$x = 2;
print $myvar, " * ", $x, " = " , ($myvar*$x), "\n";
$x = 10;
print $myvar, " * ", $x, " = " , ($myvar*$x), "\n";
$x = 75;
print $myvar, " * ", $x, " = " , ($myvar*$x), "\n";
$x = 24;
print $myvar, " * ", $x, " = " , ($myvar*$x), "\n";
